[package]
name = "siws"
version = "0.1.0"
edition = "2021"

[dependencies]
nacl = "0.5.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
time = {version = "0.3.36", features = ["serde", "formatting"]}
solana-sdk = "2.0.10"
rand = "0.8.5"
hex = "0.4.3"
